### ISSUE TITLE
关于igb驱动的疑问

### ISSUE THREAD

**Issue by itsmine** [WYC-2020/lede#3]
大佬，我看了下你关于igb驱动替换的代码。因为我的网卡是82576，所以遇到了reset adapter的问题，对此比较关注。我想问下，为什么5.15不能用新的igb驱动。我看你代码写的是5.4和5.10用这个驱动。是因为5.15还不支持吗？

**Comment by WYC-2020** [comment]
那个igb我已经恢复成用内核自带的了，我这边用这个igb，我的211网卡用不了，5.15用不了是因为5.15驱动的函数原型很多不同，不能用，可能igb还没适配5.15吧，适配了就可以用

**Comment by itsmine** [comment]
谢了，我编两个版本试试，我看igb更新了一版。如果不行就先不用网卡直通了。

**Comment by WYC-2020** [comment]
> 谢了，我编两个版本试试，我看igb更新了一版。如果不行就先不用网卡直通了。

我这边顺便修复了igb针对5.15的编译的问题，你有时间自己编译测试一下功能

**Comment by ghost** [comment]
最近编译5.10.110版本带igb-intel，启动后系统和内核日志会反复出现test 512的错误警告，请问有注意到这个问题吗？

**Comment by WYC-2020** [comment]
> 最近编译5.10.110版本带igb-intel，启动后系统和内核日志会反复出现test 512的错误警告，请问有注意到这个问题吗？

没留意，因为我不用这个驱动
