### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by afeiy** [WYC-2020/lede#4]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [* ] 没有类似的issue

### (1) 具体问题

A：腾讯云镜像仓库已经没有fakeroot_1.27.orig.tar.gz

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志

A：mkdir -p /home/afeiy/lede/dl
SHELL= flock /home/afeiy/lede/tmp/.fakeroot_1.27.orig.tar.gz.flock -c '         /home/afeiy/lede/scripts/download.pl "/home/afeiy/lede/dl" "fakeroot_1.27.orig.tar.gz" "3c45eb2d1802a2762069e2e9d21bdd6fb533592bc0cda74c9aff066ab01caddc" "" "@DEBIAN/pool/main/f/fakeroot"    '
Can't exec "aria2c": No such file or directory at /home/afeiy/lede/scripts/download.pl line 84.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://mirrors.tencent.com/debian/pool/main/f/fakeroot/fakeroot_1.27.orig.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
No more mirrors to try - giving up.
Makefile:28: recipe for target '/home/afeiy/lede/dl/fakeroot_1.27.orig.tar.gz' failed
make[3]: *** [/home/afeiy/lede/dl/fakeroot_1.27.orig.tar.gz] Error 2

**Comment by WYC-2020** [comment]
源丢失而已自己更新一下，或者用https://ftp.debian.org/debian/pool/main/f/fakeroot/fakeroot_1.27.orig.tar.gz

**Comment by WYC-2020** [comment]
@afeiy https://github.com/WYC-2020/lede/commit/836239aeb29ffa58353dcb8d5eb0f06edf0c45fd
