### ISSUE TITLE
Makefile 里是对的，为什么下载的时候错了。

### ISSUE THREAD

**Issue by keivenliao** [WYC-2020/lede#5]
![image](https://user-images.githubusercontent.com/12838693/158334616-aa40054e-2c79-4a98-9bfb-758f0a5ba724.png)

**Comment by WYC-2020** [comment]
下载失败，把地址拷贝出来手工看能访问不，如果可以那就是 再make下载的时候网络不稳或者你的梯子不好，如果不可以那就是源地址应该丢失了，这个的更新， 我看过这个地址应该是没有失效的，自己排查自己的网络情况 @keivenliao
